// <auto-generated />
using System;
using CromePlayApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CromePlayApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251230165701_InitialApp")]
    partial class InitialApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CromePlayApp.Domain.Calendar.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailablePlace")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAllDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("CalendarEvents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailablePlace = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            End = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            IsAllDay = false,
                            OwnerUserId = "MasterClub",
                            Start = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Evento de Marvel Champions",
                            Type = "CardGames"
                        },
                        new
                        {
                            Id = 2,
                            AvailablePlace = 18,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            End = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 2,
                            IsAllDay = false,
                            OwnerUserId = "MasterClub",
                            Start = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Evento de Star Wars (Unlimited)",
                            Type = "CardGames"
                        },
                        new
                        {
                            Id = 3,
                            AvailablePlace = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            End = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 3,
                            IsAllDay = false,
                            OwnerUserId = "MasterClub",
                            Start = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Evento de The Lord of the Rings",
                            Type = "CardGames"
                        },
                        new
                        {
                            Id = 4,
                            AvailablePlace = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            End = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 4,
                            IsAllDay = false,
                            OwnerUserId = "MasterClub",
                            Start = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Evento de Arkham Horror",
                            Type = "CardGames"
                        },
                        new
                        {
                            Id = 5,
                            AvailablePlace = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            End = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 5,
                            IsAllDay = false,
                            OwnerUserId = "MasterClub",
                            Start = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Evento de vampire vtes",
                            Type = "CardGames"
                        },
                        new
                        {
                            Id = 6,
                            AvailablePlace = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            End = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 6,
                            IsAllDay = false,
                            OwnerUserId = "MasterClub",
                            Start = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Evento de MAGIC. The gathering",
                            Type = "CardGames"
                        });
                });

            modelBuilder.Entity("CromePlayApp.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeBackgroundFileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("CromePlayApp.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubId"));

                    b.Property<string>("ClubDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClubEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClubName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClubId");

                    b.HasIndex("ClubEmail")
                        .IsUnique();

                    b.ToTable("Clubes");

                    b.HasData(
                        new
                        {
                            ClubId = 1,
                            ClubDescription = "Adéntrate en un mundo donde la magia y la estrategia se entrelazan. Forja tu destino como héroe, invocando criaturas legendarias, lanzando poderosos hechizos y desafiando a tus rivales en épicas batallas. Cada carta es una historia, cada jugada, una leyenda.",
                            ClubEmail = "CardGames@Contact.com",
                            ClubName = "Juegos de cartas"
                        });
                });

            modelBuilder.Entity("CromePlayApp.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("GameId1")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("MemberId1")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("GameId");

                    b.HasIndex("GameId1");

                    b.HasIndex("MemberId");

                    b.HasIndex("MemberId1");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            GameId = 1,
                            MemberId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            GameId = 1,
                            MemberId = 2
                        },
                        new
                        {
                            EnrollmentId = 3,
                            GameId = 1,
                            MemberId = 3
                        },
                        new
                        {
                            EnrollmentId = 4,
                            GameId = 1,
                            MemberId = 4
                        },
                        new
                        {
                            EnrollmentId = 5,
                            GameId = 1,
                            MemberId = 5
                        },
                        new
                        {
                            EnrollmentId = 6,
                            GameId = 2,
                            MemberId = 1
                        },
                        new
                        {
                            EnrollmentId = 7,
                            GameId = 2,
                            MemberId = 2
                        },
                        new
                        {
                            EnrollmentId = 8,
                            GameId = 2,
                            MemberId = 3
                        },
                        new
                        {
                            EnrollmentId = 9,
                            GameId = 2,
                            MemberId = 4
                        },
                        new
                        {
                            EnrollmentId = 11,
                            GameId = 3,
                            MemberId = 1
                        },
                        new
                        {
                            EnrollmentId = 12,
                            GameId = 3,
                            MemberId = 3
                        },
                        new
                        {
                            EnrollmentId = 13,
                            GameId = 3,
                            MemberId = 4
                        },
                        new
                        {
                            EnrollmentId = 14,
                            GameId = 4,
                            MemberId = 2
                        },
                        new
                        {
                            EnrollmentId = 15,
                            GameId = 4,
                            MemberId = 3
                        },
                        new
                        {
                            EnrollmentId = 16,
                            GameId = 4,
                            MemberId = 4
                        },
                        new
                        {
                            EnrollmentId = 17,
                            GameId = 4,
                            MemberId = 5
                        },
                        new
                        {
                            EnrollmentId = 18,
                            GameId = 5,
                            MemberId = 2
                        },
                        new
                        {
                            EnrollmentId = 19,
                            GameId = 5,
                            MemberId = 3
                        },
                        new
                        {
                            EnrollmentId = 20,
                            GameId = 5,
                            MemberId = 4
                        },
                        new
                        {
                            EnrollmentId = 21,
                            GameId = 6,
                            MemberId = 2
                        },
                        new
                        {
                            EnrollmentId = 22,
                            GameId = 6,
                            MemberId = 3
                        },
                        new
                        {
                            EnrollmentId = 23,
                            GameId = 6,
                            MemberId = 4
                        },
                        new
                        {
                            EnrollmentId = 24,
                            GameId = 6,
                            MemberId = 5
                        },
                        new
                        {
                            EnrollmentId = 25,
                            GameId = 6,
                            MemberId = 1
                        });
                });

            modelBuilder.Entity("CromePlayApp.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("GameDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.HasIndex("ClubId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            ClubId = 1,
                            GameDescription = "¡Entra en el universo Marvel y conviértete en tu héroe favorito! Marvel Champions es un juego cooperativo de cartas en el que tú y tus amigos uniréis fuerzas para enfrentarse a villanos icónicos y detener sus planes malvados. Cada jugador elige un héroe con habilidades únicas y construye su mazo para adaptarse a diferentes desafíos. Con partidas dinámicas, expansiones temáticas y una experiencia inmersiva, este juego te hará sentir parte de la acción. ¿Estás listo para salvar el mundo?",
                            GameName = "Marvel Champions"
                        },
                        new
                        {
                            GameId = 2,
                            ClubId = 1,
                            GameDescription = "¡Explora una galaxia muy, muy lejana en este juego de cartas coleccionable lleno de acción! Star Wars: Unlimited te permite construir tu propio mazo y enfrentarte en duelos estratégicos con héroes, villanos y naves icónicas de la saga. Con reglas dinámicas, ilustraciones espectaculares y expansiones continuas, cada partida es una nueva aventura. ¿Tienes lo necesario para liderar la batalla y cambiar el destino de la galaxia?",
                            GameName = "Star Wars (Unlimited)"
                        },
                        new
                        {
                            GameId = 3,
                            ClubId = 1,
                            GameDescription = "Embárcate en una épica aventura por la Tierra Media. Este juego cooperativo te permite liderar a héroes legendarios en misiones peligrosas contra las fuerzas oscuras de Sauron. Con mazos personalizables, escenarios desafiantes y una narrativa envolvente, The Lord of the Rings: El Juego de Cartas es la experiencia definitiva para los fans de Tolkien.",
                            GameName = "The Lord of the Rings"
                        },
                        new
                        {
                            GameId = 4,
                            ClubId = 1,
                            GameDescription = "Sumérgete en los oscuros mitos de Lovecraft con este juego cooperativo narrativo. En Arkham Horror: El Juego de Cartas, asumirás el papel de un investigador que debe resolver misterios inquietantes y enfrentarse a horrores sobrenaturales. Cada decisión cuenta: construye tu mazo, explora escenarios llenos de tensión y lucha por mantener la cordura mientras desentrañas secretos prohibidos.",
                            GameName = "Arkham Horror"
                        },
                        new
                        {
                            GameId = 5,
                            ClubId = 1,
                            GameDescription = "En Vampire: The Eternal Struggle no eres un simple jugador: eres un Matusalén, un vampiro ancestral que mueve los hilos en la oscuridad. Recluta a tu cripta, conspira, negocia y traiciona para dominar la noche. Cada decisión cuenta, cada alianza puede romperse, y solo el más astuto sobrevivirá.\r\n¿Controlarás la sangre… o serás drenado por tus rivales? La lucha nunca termina. ¿Estás listo para jugar?",
                            GameName = "vampire vtes"
                        },
                        new
                        {
                            GameId = 6,
                            ClubId = 1,
                            GameDescription = "En Magic: The Gathering te conviertes en un planeswalker, un poderoso hechicero capaz de viajar entre mundos y desatar fuerzas inimaginables. Invoca criaturas legendarias, lanza conjuros devastadores y construye estrategias únicas para derrotar a tus rivales. Cada partida es un duelo épico donde la inteligencia y la imaginación deciden el destino.",
                            GameName = "MAGIC. The gathering"
                        });
                });

            modelBuilder.Entity("CromePlayApp.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MemberAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            MemberAddress = "Calle Gran Vía 12",
                            MemberEmail = "SophieLeF@Contact.com",
                            MemberName = "Sophie Lefèvre",
                            MemberPhone = "+34 612 345 678"
                        },
                        new
                        {
                            MemberId = 2,
                            MemberAddress = "Avenida Diagonal 45",
                            MemberEmail = "AlejandroG@Contact.com",
                            MemberName = "Alejandro García",
                            MemberPhone = "+34 622 987 654"
                        },
                        new
                        {
                            MemberId = 3,
                            MemberAddress = "Calle Larios 8",
                            MemberEmail = "JulienM@Contact.com",
                            MemberName = "Julien Moreau",
                            MemberPhone = "+34 633 456 789"
                        },
                        new
                        {
                            MemberId = 4,
                            MemberAddress = "Paseo de la Castellana 221",
                            MemberEmail = "DavidW@Contact.com",
                            MemberName = "David Wilson",
                            MemberPhone = "+34 644 321 987"
                        },
                        new
                        {
                            MemberId = 5,
                            MemberAddress = "Calle Mayor 10",
                            MemberEmail = "LukasM@Contact.com",
                            MemberName = "Lukas Müller",
                            MemberPhone = "+34 655 789 123"
                        });
                });

            modelBuilder.Entity("CromePlayApp.Models.PendingUser", b =>
                {
                    b.Property<int>("PendingUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PendingUserId"));

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PendingUserEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PendingUserId");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasFilter("[IdentityUserId] IS NOT NULL AND [IdentityUserId] <> ''");

                    b.HasIndex("PendingUserEmail")
                        .IsUnique()
                        .HasFilter("[PendingUserEmail] IS NOT NULL");

                    b.ToTable("PendingUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CromePlayApp.Domain.Calendar.CalendarEvent", b =>
                {
                    b.HasOne("CromePlayApp.Models.Game", "Game")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("CromePlayApp.Models.Enrollment", b =>
                {
                    b.HasOne("CromePlayApp.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CromePlayApp.Models.Game", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("GameId1");

                    b.HasOne("CromePlayApp.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CromePlayApp.Models.Member", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("MemberId1");

                    b.Navigation("Game");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CromePlayApp.Models.Game", b =>
                {
                    b.HasOne("CromePlayApp.Models.Club", "Club")
                        .WithMany("Games")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("CromePlayApp.Models.Member", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("CromePlayApp.Models.PendingUser", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CromePlayApp.Models.Club", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("CromePlayApp.Models.Game", b =>
                {
                    b.Navigation("CalendarEvents");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CromePlayApp.Models.Member", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
